name = "Synthetic World v7"
author = "Sidpatchy"
version = "7.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "36f6ff9b09c5d0ee08ea7cbaf20de1f700b21fe93ea6df1d9f59c42224a20f6b"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
