name = "Synthetic World"
author = "Sidpatchy"
version = "8.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ec5ed2c07fe6a2dbbf205e0df4dcfa71e002690933ff05ae29d32a3868165ee3"

[versions]
minecraft = "1.19.2"
quilt = "0.18.10"

[options]
acceptable-game-versions = ["1.19", "1.19.2"]
