name = "Synthetic World"
author = "Sidpatchy"
version = "10.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "93500423bb1a333e026f1e855002caa73902519c8d51abc620d0b6794f38e78c"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.84"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
