name = "Synthetic World v7"
author = "Sidpatchy"
version = "7.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d6e374cb444a0465ac2a89e3ddef0e0a8c545d9595d82f7253839e3e4310c9f5"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
