name = "Synthetic World"
author = "Sidpatchy"
version = "10.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "815549e04fe6e5698c9b70ec5745a976d5ec37908ebf5b192bac577e709cee1f"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.84"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
