name = "Synthetic World v7"
author = "Sidpatchy"
version = "7.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "deee520d27cebbf9739a8d0ffda4f1415855eee57456a52535e1de53cee48704"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
