name = "Synthetic World"
author = "Sidpatchy"
version = "9.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "43252382c0b953bf0ac8b24e1a5128445b9b8f4b7363f9045bbc03ef66ddd062"

[versions]
minecraft = "1.20.1"
quilt = "0.21.2"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
