name = "Synthetic World"
author = "Sidpatchy"
version = "10.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bcbd574320b9e3add161854f32eb7d6363e3089c250f5a99efaae480dfcbdfe6"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.84"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
