name = "Synthetic World v6"
author = "Sidpatchy"
version = "6.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b017d980fa5419ff9fe46955bfff36e6de586b3c99fe3b76c3ce1c74cd807cb4"

[versions]
forge = "36.1.16"
minecraft = "1.16.5"
