name = "Synthetic World v7"
author = "Sidpatchy"
version = "7.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "04fb8ede67b04a4ca97af82a5f9e0273b768f2eff36a6c6517b744d843a74603"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
