name = "Additional Enchanted Miner"
filename = "AdditionalEnchantedMiner-1.18-fabric-18.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3599/210/AdditionalEnchantedMiner-1.18-fabric-18.2.0.jar"
hash-format = "murmur2"
hash = "3455110034"

[update]
[update.curseforge]
file-id = 3599210
project-id = 282837
