name = "Additional Enchanted Miner"
filename = "AdditionalEnchantedMiner-1.18-fabric-18.2.519.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3732/991/AdditionalEnchantedMiner-1.18-fabric-18.2.519.jar"
hash-format = "murmur2"
hash = "628448936"

[update]
[update.curseforge]
file-id = 3732991
project-id = 282837
