name = "Additional Enchanted Miner"
filename = "AdditionalEnchantedMiner-1.18-fabric-18.2.493.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3644/590/AdditionalEnchantedMiner-1.18-fabric-18.2.493.jar"
hash-format = "murmur2"
hash = "2865546185"

[update]
[update.curseforge]
file-id = 3644590
project-id = 282837
