name = "Alternate Current"
filename = "alternate-current-mc1.18-1.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3745/901/alternate-current-mc1.18-1.2.0.jar"
hash-format = "murmur2"
hash = "3054111139"

[update]
[update.curseforge]
file-id = 3745901
project-id = 548115
