name = "[ANGRY PIXEL] The Betweenlands"
filename = "TheBetweenlands-3.7.3-universal.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3248/202/TheBetweenlands-3.7.3-universal.jar"
hash-format = "murmur2"
hash = "729022150"

[update]
[update.curseforge]
file-id = 3248202
project-id = 243363
