name = "Applied Energistics 2"
filename = "appliedenergistics2-10.1.0-beta.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3646/160/appliedenergistics2-10.1.0-beta.2.jar"
hash-format = "murmur2"
hash = "2522623173"

[update]
[update.curseforge]
file-id = 3646160
project-id = 223794
