name = "Architectury API (Fabric)"
filename = "architectury-3.8.51.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3760/639/architectury-3.8.51.jar"
hash-format = "murmur2"
hash = "2752098245"

[update]
[update.curseforge]
file-id = 3760639
project-id = 419697
