name = "Auto Config Updated API"
filename = "autoconfig1u-3.4.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3668/220/autoconfig1u-3.4.0.jar"
hash-format = "murmur2"
hash = "2542736805"

[update]
[update.curseforge]
file-id = 3668220
project-id = 373261
