name = "Better Animals Plus"
filename = "betteranimalsplus-1.18.1-11.0.5-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3680/859/betteranimalsplus-1.18.1-11.0.5-fabric.jar"
hash-format = "murmur2"
hash = "1821460338"

[update]
[update.curseforge]
file-id = 3680859
project-id = 303557
