name = "Better Animals Plus"
filename = "betteranimalsplus-1.16.5-10.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3286/395/betteranimalsplus-1.16.5-10.2.0.jar"
hash-format = "murmur2"
hash = "1649013136"

[update]
[update.curseforge]
file-id = 3286395
project-id = 303557
