name = "Blockus"
filename = "blockus-2.3.11+1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3766/41/blockus-2.3.11+1.18.1.jar"
hash-format = "murmur2"
hash = "1707168062"

[update]
[update.curseforge]
file-id = 3766041
project-id = 312289
