name = "Bosses of Mass Destruction"
filename = "BOMD-1.3.5-1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3635/839/BOMD-1.3.5-1.18.jar"
hash-format = "murmur2"
hash = "1569878187"

[update]
[update.curseforge]
file-id = 3635839
project-id = 438365
