name = "Client Tweaks"
filename = "ClientTweaks_1.12.2-3.1.11.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2624/712/ClientTweaks_1.12.2-3.1.11.jar"
hash-format = "murmur2"
hash = "3397426670"

[update]
[update.curseforge]
file-id = 2624712
project-id = 251407
