name = "Controlling"
filename = "Controlling-7.0.0.15.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3281/360/Controlling-7.0.0.15.jar"
hash-format = "murmur2"
hash = "1211830978"

[update]
[update.curseforge]
file-id = 3281360
project-id = 250398
