name = "DashLoader"
filename = "dashloader-def-3.1.1+1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3720/646/dashloader-def-3.1.1+1.18.jar"
hash-format = "murmur2"
hash = "633757925"

[update]
[update.curseforge]
file-id = 3720646
project-id = 472772
