name = "Effective 💦"
filename = "effective-1.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3735/265/effective-1.2.jar"
hash-format = "murmur2"
hash = "3729215890"

[update]
[update.curseforge]
file-id = 3735265
project-id = 556381
