name = "Engineer's Decor"
filename = "engineersdecor-1.12.2-1.1.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3033/266/engineersdecor-1.12.2-1.1.2.jar"
hash-format = "murmur2"
hash = "1514029164"

[update]
[update.curseforge]
file-id = 3033266
project-id = 313866
