name = "Entity Culling Fabric/Forge"
filename = "entityculling-fabric-mc1.18-1.5.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3743/933/entityculling-fabric-mc1.18-1.5.1.jar"
hash-format = "murmur2"
hash = "361840395"

[update]
[update.curseforge]
file-id = 3743933
project-id = 448233
