name = "Environmental Tech"
filename = "envirotech-1.16.5-3.0.8.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3260/560/envirotech-1.16.5-3.0.8.0.jar"
hash-format = "murmur2"
hash = "3105286439"

[update]
[update.curseforge]
file-id = 3260560
project-id = 245453
