name = "Fabric Seasons"
filename = "fabric-seasons-1.3-BETA+1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3540/833/fabric-seasons-1.3-BETA+1.18.jar"
hash-format = "murmur2"
hash = "2953920511"

[update]
[update.curseforge]
file-id = 3540833
project-id = 413523
