name = "Friendly Fire"
filename = "FriendlyFire-1.16.5-7.0.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3232/429/FriendlyFire-1.16.5-7.0.2.jar"
hash-format = "murmur2"
hash = "1865902482"

[update]
[update.curseforge]
file-id = 3232429
project-id = 255105
