name = "Hats"
filename = "Hats-1.12.2-7.1.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2960/397/Hats-1.12.2-7.1.1.jar"
hash-format = "murmur2"
hash = "4240845981"

[update]
[update.curseforge]
file-id = 2960397
project-id = 229073
