name = "Immersive Petroleum"
filename = "ImmersivePetroleum-1.16.5-3.2.0-3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3235/657/ImmersivePetroleum-1.16.5-3.2.0-3.jar"
hash-format = "murmur2"
hash = "1820521994"

[update]
[update.curseforge]
file-id = 3235657
project-id = 268250
