name = "Indium"
filename = "indium-1.0.2-alpha3+mc1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3667/666/indium-1.0.2-alpha3+mc1.18.1.jar"
hash-format = "murmur2"
hash = "2346740674"

[update]
[update.curseforge]
file-id = 3667666
project-id = 459496
