name = "Industrial Craft"
filename = "industrialcraft-2-2.8.170-ex112.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2746/892/industrialcraft-2-2.8.170-ex112.jar"
hash-format = "murmur2"
hash = "3916953727"

[update]
[update.curseforge]
file-id = 2746892
project-id = 242638
