name = "Inventory Sorter"
filename = "inventorysorter-1.12.2-1.13.3+57.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2546/769/inventorysorter-1.12.2-1.13.3+57.jar"
hash-format = "murmur2"
hash = "3283463975"

[update]
[update.curseforge]
file-id = 2546769
project-id = 240633
