name = "Iron Jetpacks"
filename = "IronJetpacks-1.16.4-4.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3173/404/IronJetpacks-1.16.4-4.2.0.jar"
hash-format = "murmur2"
hash = "293993172"

[update]
[update.curseforge]
file-id = 3173404
project-id = 284497
