name = "Iron Jetpacks Fabric"
filename = "iron-jetpacks-0.4.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3578/788/iron-jetpacks-0.4.3.jar"
hash-format = "murmur2"
hash = "1106073267"

[update]
[update.curseforge]
file-id = 3578788
project-id = 386892
