name = "JEI Integration"
filename = "jeiintegration_1.12.2-1.6.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2951/731/jeiintegration_1.12.2-1.6.0.jar"
hash-format = "murmur2"
hash = "1053708721"

[update]
[update.curseforge]
file-id = 2951731
project-id = 265917
