name = "LemonLib"
filename = "lemonlib-1.12.2-1.3.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2639/879/lemonlib-1.12.2-1.3.0.jar"
hash-format = "murmur2"
hash = "1982833992"

[update]
[update.curseforge]
file-id = 2639879
project-id = 306926
