name = "Litematica"
filename = "litematica-fabric-1.18.1-0.10.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3671/382/litematica-fabric-1.18.1-0.10.4.jar"
hash-format = "murmur2"
hash = "3103873847"

[update]
[update.curseforge]
file-id = 3671382
project-id = 308892
