name = "Macaw's Trapdoors"
filename = "mcw-trapdoors-1.0.2-mc1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3273/512/mcw-trapdoors-1.0.2-mc1.16.5.jar"
hash-format = "murmur2"
hash = "293957677"

[update]
[update.curseforge]
file-id = 3273512
project-id = 400933
