name = "MaLiLib"
filename = "malilib-fabric-1.18.1-0.11.8.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3671/369/malilib-fabric-1.18.1-0.11.8.jar"
hash-format = "murmur2"
hash = "2492474394"

[update]
[update.curseforge]
file-id = 3671369
project-id = 303119
