name = "megane"
filename = "megane-7.1.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3648/827/megane-7.1.2.jar"
hash-format = "murmur2"
hash = "2089735621"

[update]
[update.curseforge]
file-id = 3648827
project-id = 408118
