name = "MJRLegends Lib"
filename = "MJRLegendsLib-1.12.2-1.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3029/768/MJRLegendsLib-1.12.2-1.2.0.jar"
hash-format = "murmur2"
hash = "2228550568"

[update]
[update.curseforge]
file-id = 3029768
project-id = 284331
