name = "Modern Industrialization"
filename = "Modern-Industrialization-1.0.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3646/911/Modern-Industrialization-1.0.5.jar"
hash-format = "murmur2"
hash = "58608337"

[update]
[update.curseforge]
file-id = 3646911
project-id = 405388
