name = "Space Dimensions (Fabric)"
filename = "agape_space_18_1-0.5.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3681/477/agape_space_18_1-0.5.4.jar"
hash-format = "murmur2"
hash = "438632868"

[update]
[update.curseforge]
file-id = 3681477
project-id = 429841
