name = "Space Dimensions (Fabric)"
filename = "agape_space_18_1-0.5.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3606/648/agape_space_18_1-0.5.0.jar"
hash-format = "murmur2"
hash = "1452232659"

[update]
[update.curseforge]
file-id = 3606648
project-id = 429841
