name = "Space Dimensions (Fabric)"
filename = "agape_space_18_1-0.5.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3642/794/agape_space_18_1-0.5.3.jar"
hash-format = "murmur2"
hash = "509164389"

[update]
[update.curseforge]
file-id = 3642794
project-id = 429841
