name = "Mouse Wheelie (Fabric)"
filename = "mousewheelie-1.8.8+mc1.18-pre5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3717/989/mousewheelie-1.8.8+mc1.18-pre5.jar"
hash-format = "murmur2"
hash = "42109187"

[update]
[update.curseforge]
file-id = 3717989
project-id = 317514
