name = "No Recipe Book"
filename = "noRecipeBook_v1.2.2formc1.12.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2568/865/noRecipeBook_v1.2.2formc1.12.2.jar"
hash-format = "murmur2"
hash = "1336617140"

[update]
[update.curseforge]
file-id = 2568865
project-id = 284904
