name = "PlayerAbilityLib"
filename = "pal-1.5.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3751/370/pal-1.5.1.jar"
hash-format = "murmur2"
hash = "2131829807"

[update]
[update.curseforge]
file-id = 3751370
project-id = 359522
