name = "PlayerAbilityLib"
filename = "pal-1.5.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3541/576/pal-1.5.0.jar"
hash-format = "murmur2"
hash = "2611075206"

[update]
[update.curseforge]
file-id = 3541576
project-id = 359522
