name = "Pipe"
filename = "pipe-1.18-1.6.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3630/639/pipe-1.18-1.6.2.jar"
hash-format = "murmur2"
hash = "2755947974"

[update]
[update.curseforge]
file-id = 3630639
project-id = 441787
