name = "Placebo"
filename = "Placebo-1.16.4-4.4.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3281/276/Placebo-1.16.4-4.4.2.jar"
hash-format = "murmur2"
hash = "2308893429"

[update]
[update.curseforge]
file-id = 3281276
project-id = 283644
