name = "Railcraft"
filename = "railcraft-12.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2687/757/railcraft-12.0.0.jar"
hash-format = "murmur2"
hash = "4261977453"

[update]
[update.curseforge]
file-id = 2687757
project-id = 51195
