name = "Reborn Core"
filename = "RebornCore-1.12.2-3.19.4.529-universal.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2966/845/RebornCore-1.12.2-3.19.4.529-universal.jar"
hash-format = "murmur2"
hash = "4053697309"

[update]
[update.curseforge]
file-id = 2966845
project-id = 237903
