name = "SecretRoomsMod"
filename = "secretroomsmod-1.12.2-5.6.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2561/617/secretroomsmod-1.12.2-5.6.4.jar"
hash-format = "murmur2"
hash = "1776855339"

[update]
[update.curseforge]
file-id = 2561617
project-id = 59652
