name = "spark"
filename = "spark-1.9.1-fabric.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/l6YH9Als/versions/1.9.1-fabric/spark-1.9.1-fabric.jar"
hash-format = "sha512"
hash = "c7b9691096658f6d53de41f0be3ee64a9bb9275620493f1ce3366e08b9eed55010217e4d8479d91bb9f142e16c6776a7ef9703f6f6fef8b40ff87e29dd1b11d3"

[update]
[update.modrinth]
mod-id = "l6YH9Als"
version = "qBdtA5uj"
