name = "SpatialCompat"
filename = "spatialservermod-1.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2525/554/spatialservermod-1.3.jar"
hash-format = "murmur2"
hash = "3568098340"

[update]
[update.curseforge]
file-id = 2525554
project-id = 277136
