name = "Stoneholm, Underground Villages (Fabric)"
filename = "stoneholm-1.4.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3631/590/stoneholm-1.4.2.jar"
hash-format = "murmur2"
hash = "1833373070"

[update]
[update.curseforge]
file-id = 3631590
project-id = 460336
