name = "Sync"
filename = "Sync-1.12.2-7.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2682/824/Sync-1.12.2-7.1.0.jar"
hash-format = "murmur2"
hash = "1946839867"

[update]
[update.curseforge]
file-id = 2682824
project-id = 229090
