name = "Track API"
filename = "TrackAPI-1.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2825/260/TrackAPI-1.2.jar"
hash-format = "murmur2"
hash = "2373647602"

[update]
[update.curseforge]
file-id = 2825260
project-id = 282613
