name = "Trinkets (Fabric)"
filename = "trinkets-3.2.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3723/674/trinkets-3.2.1.jar"
hash-format = "murmur2"
hash = "1099024845"

[update]
[update.curseforge]
file-id = 3723674
project-id = 341284
