name = "Universal Graves"
filename = "graves-2.0.0-rc.5+1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3662/452/graves-2.0.0-rc.5+1.18.1.jar"
hash-format = "murmur2"
hash = "937785447"

[update]
[update.curseforge]
file-id = 3662452
project-id = 497175
