name = "Universal Graves"
filename = "graves-2.0.0-beta.4.2+1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3624/452/graves-2.0.0-beta.4.2+1.18.1.jar"
hash-format = "murmur2"
hash = "3608866927"

[update]
[update.curseforge]
file-id = 3624452
project-id = 497175
