name = "Wawla - What Are We Looking At"
filename = "Wawla-1.12.2-2.6.275.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2916/368/Wawla-1.12.2-2.6.275.jar"
hash-format = "murmur2"
hash = "1231381817"

[update]
[update.curseforge]
file-id = 2916368
project-id = 224712
