name = "Waystones (Fabric Edition)"
filename = "waystones-fabric-1.18.1-9.0.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3658/45/waystones-fabric-1.18.1-9.0.4.jar"
hash-format = "murmur2"
hash = "3279061923"

[update]
[update.curseforge]
file-id = 3658045
project-id = 500087
