name = "Wither Skeleton Tweaks"
filename = "Wither-Skeleton-Tweaks-1.16.4-5.3.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3172/803/Wither-Skeleton-Tweaks-1.16.4-5.3.0.jar"
hash-format = "murmur2"
hash = "169920213"

[update]
[update.curseforge]
file-id = 3172803
project-id = 255902
