name = "WTHIT"
filename = "wthit-fabric-4.5.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3707/3/wthit-fabric-4.5.5.jar"
hash-format = "murmur2"
hash = "3389509705"

[update]
[update.curseforge]
file-id = 3707003
project-id = 440979
